tasks:
  - init: cargo install just cargo-hack cargo-watch cargo-msrv cargo-deny && cargo update && just verify
    command: just watch

vscode:
  extensions:
    - rust-lang.rust-analyzer

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
