[hooks]
"before:init" = "just verify-for-release"
"before:git:bump" = "just verify"
"before:release" = "just publish"

[git]
requireBranch = "main"

[github]
release = true

[plugins."@release-it/keep-a-changelog"]
filename = "CHANGELOG.md"
strictLatest = false
addUnreleased = true
addVersionUrl = true

[plugins."@release-it/bumper"]
in = { file = "Cargo.toml", path = "package.version" }

[plugins."@j-ulrich/release-it-regex-bumper"]
out = [
    { file = "src/**/*.rs", search = "since = \"<NEXT>\"", replace = "since = \"{{version}}\"" },
    { file = "Cargo.toml", search = "version = \"\\d+\\.\\d+\\.\\d+(-.+)?\" # auto-update", replace = "version = \"{{version}}\" # auto-update" },
]
