[package]
name = "beancount-parser-2"
version = "1.0.0-alpha.0"
license = "Unlicense"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.69.0"
description = "A beancount file parser library for rust"
repository = "https://github.com/jcornaz/beancount-parser-2"
categories = ["parser-implementations"]
keywords = ["parsing", "beancount", "accounting"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
nom = { version = "7.1", default-features = false, features = ["std"] }
nom_locate = { version = "4.1", default-features = false }
rust_decimal = { version = "1.29", default-features = false }
thiserror = { version = "1.0", default-features = false }

[dev-dependencies]
criterion = "0.4.0"
rstest = { version = "0.17.0", default-features = false }

[[bench]]
name = "benchmark"
harness = false
