[package]
name = "beancount-parser"
version = "1.14.0"
license = "Unlicense"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.60.0"
description = "A beancount file parser library for rust"
repository = "https://github.com/jcornaz/beancount-parser"
categories = ["parser-implementations"]
keywords = ["parsing", "beancount", "accounting"]

[package.metadata.docs.rs]
all-features = true

[features]
unstable = ["pest", "pest_derive"]
rust_decimal = []

[dependencies]
nom = "7.1"
rust_decimal = { version = "1.28", default-features = false }
thiserror = "1.0"
pest = { version = "2.5", default-features = false, features = ["std"], optional = true }
pest_derive = { version = "2.5", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
rstest = { version = "0.16.0", default-features = false }

[build-dependencies]
rustc_version = "0.4.0"

[profile.dev]
opt-level = 1
debug = false

[profile.release]
lto = true
codegen-units = 1
