[package]
name = "beancount-parser"
version = "0.0.0-dev"
license = "Unlicense"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.62"
description = ""
repository = "https://github.com/jcornaz/beancount-parser"

[dependencies]
nom = "7.1"
rust_decimal = { version = "1.26", default-features = false }

[dev-dependencies]
rstest = { version = "0.15.0", default-features = false }

[profile.dev]
opt-level = 1
debug = false

[profile.release]
lto = true
codegen-units = 1
