[advisories]
yanked = "deny"
ignore = []

[licenses]
unused-allowed-license = "allow"
allow = [
  "Unlicense",
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
  "ISC"
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
