name: verify

on:
  push:
    branches: ["[0-9]+.x", main, rc, beta, alpha]
  pull_request:
  workflow_dispatch:

env:
  RUST_VERSION: "1.65"
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - uses: extractions/setup-just@v1
      - run: just verify
